# Generated by Django 6.0 on 2025-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cuisine_remove_restaurant_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
