# Generated by Django 6.0 on 2025-12-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dish_featured_restaurant_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
